[project]
name = "JobSelect"
version = "0.12.7"
dependencies = [
  "rich==15.0.0",
  "textual==8.2.8",
  "pyfiglet==1.0.4",
  "scikit-learn==1.9.0",
  "uvicorn==0.50.2",
  "pydantic==2.13.4",
  "requests==2.34.2",
  "torch==2.12.1",
  "dotenv==0.9.9"
]
description = "A CLI Based AI Skill Classifier for Job Descriptions Build by Akshay Babu"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
authors = [
  { name="Akshay Babu", email="akshaysureshbabu100@gmail.com" },
]

[project.urls]
Website = "https://jobselect.vercel.app"
GitHub = "https://github.com/Ak47xdd/Job-Description-Analysis"
"Huggging Face (Model)" = "https://huggingface.co/JobSelect/JobAnalyze_6k"
"Hugging Face (Dataset)" = "https://huggingface.co/datasets/JobSelect/Job-Descriptions-JobAnalyze_6k"
"LinkedIn Company Page" = "https://www.linkedin.com/company/jobselect-labs"

# CLI entrypoint
[project.scripts]
jobselect = "cli.jobselect:cli"

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = [
  "cli*",
  "model*", 
  "model/prep*", 
  "model/prep/v1*", 
  "model/prep/v2*", 
  "model_out*", 
  "model_out/v1*", 
  "model_out/v2*",
  "frontend*",
  "frontend/repo*", 
  "api*", 
  "api/JobAnalyze*", 
  "api/JobAnalyze/v1*", 
  "api/JobAnalyze/v2*"
  ]
exclude = [
  "data*", 
  "notebooks*", 
  "test*"
  ]

[tool.setuptools.package-data]
"model.prep.v1" = ["label_vocab.json", "vectorizer.pkl", "prepared_data.npz"]
"model_out.v1" = ["skill_classifier.pt", "training_history.json"]
"model.prep.v2" = ["label_vocab_v2.json", "vectorizer_v2.pkl", "prepared_data_v2.npz"]
"model_out.v2" = ["skill_classifier_v2.pt", "training_history_v2.json"]
